### ISSUE TITLE
Only returning "😶" as replies.

### ISSUE THREAD

**Issue by SavageTheUnicorn** [zhaobenny/bz-cogs#1]
As far as I know I've done everything right and I have the cog fully configured and using my api token. Is there something obvious that I'm missing?

**Comment by DJTOMATO** [comment]
Currently it's working fine for me, I usually get 😶 when you talk moderated stuff to the bot.

Have you tried talking normal stuff to it?

Also, when there's a error or a 😶 response there should be something in your bot logs, if ur on linux try ``journalctl -feu redbot``
Source: https://github.com/zhaobenny/bz-cogs/blob/c511c968de67bedf12fc67fc036248eb5951cf52/ai_user/response/response.py#L25

**Comment by SavageTheUnicorn** [comment]
> Currently it's working fine for me, I usually get 😶 when you talk moderated stuff to the bot.
> 
> Have you tried talking normal stuff to it?
> 
> Also, when there's a error or a 😶 response there should be something in your bot logs, if ur on linux try ``journalctl -feu redbot``
> Source: https://github.com/zhaobenny/bz-cogs/blob/c511c968de67bedf12fc67fc036248eb5951cf52/ai_user/response/response.py#L25

Yes, I've tried with normal chats and same result. I tried ``journalctl -feu redbot`` but no output was ever produced.

**Comment by DJTOMATO** [comment]
Well, you should replace redbot with your bot instance/service name. It was an example.

**Comment by SavageTheUnicorn** [comment]
> Well, you should replace redbot with your bot instance/service name. It was an example.

My instance name IS redbot actually. I'll double check though.

**Comment by DJTOMATO** [comment]
journalctl should output the bot console, you could also try ``sudo service botname status``

**Comment by SavageTheUnicorn** [comment]
> journalctl should output the bot console, you could also try ``sudo service botname status``
> 

Name was red@redbot surprisingly. I'm getting an error stating that I've exceeded my quota, but I can use chatgpt just fine.

**Comment by DJTOMATO** [comment]
> > journalctl should output the bot console, you could also try `sudo service botname status`
> 
> Name was red@redbot surprisingly. I'm getting an error stating that I've exceeded my quota, but I can use chatgpt just fine. I generated a brand new api key to use for this, so it was in my clipboard making mistyping it impossible. Is this a plus account only thing?

It's not a plus thing, but from my previous experience, api keys might still work up to 48 hours after expired/overquota'd.

If you're using a trial account, and you're out of credits, well it's gg ~~unless you create another trial account~~

**Comment by SavageTheUnicorn** [comment]
> > > journalctl should output the bot console, you could also try `sudo service botname status`
> > 
> > Name was red@redbot surprisingly. I'm getting an error stating that I've exceeded my quota, but I can use chatgpt just fine. I generated a brand new api key to use for this, so it was in my clipboard making mistyping it impossible. Is this a plus account only thing?
> 
> It's not a plus thing, but from my previous experience, api keys might still work up to 48 hours after expired/overquota'd.
> 
> If you're using a trial account, and you're out of credits, well it's gg ~~unless you create another trial account~~

Ahhhh. My trial credits expired a week ago. Thanks for the quick help!

**Comment by zhaobenny** [comment]
Thanks for the help, @DJTOMATO! 🔥
