### ISSUE TITLE
ollama support (Local LLMs)

### ISSUE THREAD

**Issue by CorneliusCornbread** [zhaobenny/bz-cogs#35]
Correct me if I'm wrong but it seems the cog doesn't support locally hosted LLM models. Most notable of which would be something like [Ollama](https://github.com/jmorganca/ollama), or possibly something like [h2ogpt](https://github.com/h2oai/h2ogpt).

It'd be really nice to avoid having to pay for the usage of this cog via hosting locally.

**Comment by zhaobenny** [comment]
The `aiuser` cog does [supports setting alternative OpenAI API servers.](https://github.com/zhaobenny/bz-cogs/tree/main/aiuser#custom-openai-endpoint) (as long as they are compatible with the more recent OpenAI clients packages)

h2ogpt seems to [provide a OpenAI proxy](https://github.com/h2oai/h2ogpt/blob/main/docs/README_InferenceServers.md#openai-proxy-inference-server-client) so it _might_ work out of the box, but Ollama doesn't and probably needs something like [litellm.](https://github.com/BerriAI/litellm)
