### ISSUE TITLE
[Enhancement ] New Configurable Trigger

### ISSUE THREAD

**Issue by egundersen** [zhaobenny/bz-cogs#44]
It would be nice if the bot would only respond when users are having a conversation with it.

How it could work in practice:
- Bot owner sets reply_percent to something really low, like `-aiuser percent 0.01`
- Users trigger a conversation via @X.XX'ing the bot, a random message, or reply_percent as per normal.

> Bot may continue to reply to new messages if no more than `conversation_reply_time` seconds have passed since the last message.
> - `conversation_reply_time = 60` (setting to zero disables the feature)
> - `conversation_reply_percent = 0.5` (50% chance to trigger a reply within the `conversation_reply_time` time frame

This feature request is basically asking for 2 configurable variables for a new way to trigger responses.

**Comment by zhaobenny** [comment]
Great suggestion, makes sense!

will implement in the future..

**Comment by zhaobenny** [comment]
implemented  by  e583d57f7f444188a4c5e1f94fa14658a0de84c6

currently it works off a timer off the last bot message (if there's too much side effects, i'll swap it to working off the last message instead as suggested)

the commands are `[p]aiuser trigger conversation_reply_percent` and `[p]aiuser trigger conversation_reply_time`
