### ISSUE TITLE
[aimage] Remote setup

### ISSUE THREAD

**Issue by QuentinJ54** [zhaobenny/bz-cogs#47]
Good morning,

I have my bot which is on Docker and my Stable Diffusion which is on a remote computer, how can I make the link between the two? I added the "--api -listen" parameters, however with these it deactivates the API /sdapi/v1/txt2img.

**Comment by zhaobenny** [comment]
`--api --listen` shouldn't deactivate the API on the Automatic1111 instance..?

Is the Redbot instance and Automatic1111 instance on the same host? If not, you'll need to some additional networking.

**Comment by QuentinJ54** [comment]
it activates the API but the /sdapi/v1/txt2img part is missing

**Comment by zhaobenny** [comment]
http://127.0.0.1:7860/docs#/default/text2imgapi_sdapi_v1_txt2img_post

you don't have this? are you on the latest version of Automatic1111?

**Comment by QuentinJ54** [comment]
When I put the parameter `--api` it is present but if I add `--listend` it is no longer available..
It is possible that this function is not available for remote equipment?

**Comment by zhaobenny** [comment]
the A1111 doc for `--listen` is https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings#:~:text=Running%20within%20Local%20Area%20Network

If the cog works without it, I guess you dont need it?

**Comment by QuentinJ54** [comment]
my bot is located on another machine so it is necessary for me to make Stable Diffusion accessible remotely for contact using the `--listend` option

**Comment by zhaobenny** [comment]
Make sure you are setting your command line arguments properly in A1111?

Else, try asking in the Automatic1111 [repo](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions) for better assistance

**Comment by QuentinJ54** [comment]
Okay, thank you for your time and help
