### ISSUE TITLE
aichat discord

### ISSUE THREAD

**Issue by TsukamotoMari** [zhaobenny/bz-cogs#50]
im using red discord bot self hosted and im setting up aichat and its only using sleep emoji? what am i doing wrong i even set the api key

**Comment by zhaobenny** [comment]
Can you check your bot logs? Are there any errors?

**Comment by zhaobenny** [comment]
Resolved by checking bot logs, was ratelimited trial account

**Comment by TsukamotoMari** [comment]
figured it out on discord thanks!
